Presentacion/Models/ErrorViewModel.cs
namespace Presentacion.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentacion/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Presentacion.Models;
using System.Diagnostics;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentacion/Controllers/TareaController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo;

namespace Presentacion.Controllers
{
    public class TareaController : Controller
    {
        public IActionResult GetAll()
        {
            Modelo.Tarea tarea = new Modelo.Tarea();
            Modelo.Result result = Negocio.Tarea.GetAllLINQ();

            tarea.Estado = new Modelo.Estado();
            Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
            tarea.Estado.Estados = resultEstados.Objects;

            tarea.Prioridad = new Modelo.Prioridad();
            Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
            tarea.Prioridad.Prioridades = resultPrioridad.Objects;

            tarea.Categoria = new Modelo.Categoria();
            Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
            tarea.Categoria.Categorias = resultCategoria.Objects;


            if (result.Correct)
            {
                tarea.Tareas = result.Objects;
                return View(tarea);
            }
            else
            {
                return View(tarea);
            }
        }
        [HttpPost]
        public IActionResult GetAll(string palabra)
        {
            Modelo.Tarea tarea = new Modelo.Tarea();
            palabra = (palabra == null) ? "" : palabra;

            Modelo.Result result = Negocio.Tarea.BusquedaAbierta(palabra);


            if (result.Correct)
            {
                tarea.Estado = new Modelo.Estado();
                Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
                tarea.Estado.Estados = resultEstados.Objects;

                tarea.Prioridad = new Modelo.Prioridad();
                Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
                tarea.Prioridad.Prioridades = resultPrioridad.Objects;

                tarea.Categoria = new Modelo.Categoria();
                Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
                tarea.Categoria.Categorias = resultCategoria.Objects;

                tarea.Tareas = result.Objects;
                return View(tarea);
            }
            else
            {
                return View(tarea);
            }
        }
        [HttpGet]
        public JsonResult GetAllJson()
        {
            Modelo.Tarea tarea = new Modelo.Tarea();
            Modelo.Result result = Negocio.Tarea.GetAllLINQ();

            tarea.Estado = new Modelo.Estado();
            Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
            tarea.Estado.Estados = resultEstados.Objects;

            tarea.Prioridad = new Modelo.Prioridad();
            Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
            tarea.Prioridad.Prioridades = resultPrioridad.Objects;

            tarea.Categoria = new Modelo.Categoria();
            Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
            tarea.Categoria.Categorias = resultCategoria.Objects;


            if (result.Correct)
            {
                tarea.Tareas = result.Objects;
                return Json(tarea);
            }
            else
            {
                return Json(tarea);
            }
        }
        [HttpGet]
        public JsonResult GetAllPersonal()
        {
            Modelo.Tarea tarea = new Modelo.Tarea();
            Modelo.Result result = Negocio.Tarea.GetAllPersonal();

            tarea.Estado = new Modelo.Estado();
            Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
            tarea.Estado.Estados = resultEstados.Objects;

            tarea.Prioridad = new Modelo.Prioridad();
            Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
            tarea.Prioridad.Prioridades = resultPrioridad.Objects;

            tarea.Categoria = new Modelo.Categoria();
            Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
            tarea.Categoria.Categorias = resultCategoria.Objects;


            if (result.Correct)
            {
                tarea.Tareas = result.Objects;
                return Json(tarea);
            }
            else
            {
                return Json(tarea);
            }
        }
        [HttpGet]
        public JsonResult GetAllProfesional()
        {
            Modelo.Tarea tarea = new Modelo.Tarea();
            Modelo.Result result = Negocio.Tarea.GetAllProfesional();

            tarea.Estado = new Modelo.Estado();
            Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
            tarea.Estado.Estados = resultEstados.Objects;

            tarea.Prioridad = new Modelo.Prioridad();
            Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
            tarea.Prioridad.Prioridades = resultPrioridad.Objects;

            tarea.Categoria = new Modelo.Categoria();
            Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
            tarea.Categoria.Categorias = resultCategoria.Objects;


            if (result.Correct)
            {
                tarea.Tareas = result.Objects;
                return Json(tarea);
            }
            else
            {
                return Json(tarea);
            }
        }
        [HttpGet]
        public JsonResult GetById(byte idTarea)
        {
            Modelo.Tarea tarea = new Modelo.Tarea();

            //Get all Estado, Prioridad y Categoria
            tarea.Estado = new Modelo.Estado();
            Modelo.Result resultEstados = Negocio.Estado.GetAllLINQ();
            tarea.Estado.Estados = resultEstados.Objects;

            tarea.Prioridad = new Modelo.Prioridad();
            Modelo.Result resultPrioridad = Negocio.Prioridad.GetAllLINQ();
            tarea.Prioridad.Prioridades = resultPrioridad.Objects;

            tarea.Categoria = new Modelo.Categoria();
            Modelo.Result resultCategoria = Negocio.Categoria.GetAllLINQ();
            tarea.Categoria.Categorias = resultCategoria.Objects;

            Modelo.Result result = new Modelo.Result();

            result = Negocio.Tarea.GetByIdLINQ(idTarea);

            return Json(result);
        }
        [HttpPost]
        public JsonResult GuardarTarea(Modelo.Tarea tarea)
        {
            Modelo.Result result = new Modelo.Result();
            //if (ModelState.IsValid)
            //{
            if (tarea.IdTarea == 0)
            {
                //Add
                result = Negocio.Tarea.AddLINQ(tarea);
                if (result.Correct)
                {
                    return Json(result);
                }
            }
            else
            {
                //Update
                result = Negocio.Tarea.UpdateLINQ(tarea);
                if (result.Correct)
                {
                    return Json(result);
                }
            }
            //}
            //else
            //{
            //    return Json(tarea);
            //}
            return Json(tarea);
        }
        [HttpGet]
        public JsonResult Delete(byte idTarea)
        {
            Modelo.Result result = Negocio.Tarea.DeleteLINQ(idTarea);
            if (result.Correct)
            {
                return Json(result);
            }
            else
            {
                return Json(result);
            }
        }

        [HttpPost]
        public JsonResult CambiarEstatus(byte idEstatus, byte idTarea)
        {
            Modelo.Result result = Negocio.Tarea.UpdateEstado(idEstatus, idTarea);

            if (result.Correct)
            {
                return Json(result);
            }
            return Json(result);
        }
    }
}

Presentacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To do List</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/Quartz.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentacion.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Mi Lista</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarea" asp-action="GetAll">To-Do List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Presentacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>